{{- if .Values.peerauthentication.enabled -}}
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "default"
spec:
  mtls:
    mode: STRICT
---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "istio-system"
  namespace: "istio-system"
spec:
  mtls:
    mode: STRICT
{{- end }}